// Generated by nyrc 0.2.0 (NYR-Lang) from smarttick/src/main/nyr/hysteresis.nyr -- do not edit.
// source sha256 e591ddf7bd8a0c8e73e6f0c42fd8060a710c02b38b914bc5712b94fe3f1c7d48
package com.nyr.guardian.smarttick;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * Rules compiled from smarttick/src/main/nyr/hysteresis.nyr by nyrc 0.2.0.  {@link #evaluate(Context)} returns the spawns,
 * signals and updates of every rule whose condition holds, in rule order.  Numbers are double;
 * an update's {@link Op} says whether it replaces (SET) or adds to (ADD) the output it names.
 */
public final class HysteresisRules {
    private HysteresisRules() {}

    public static final List<String> INPUTS = List.of("behind", "pressure", "high_since", "hold", "now", "recovered_at", "min_behind", "low_since", "behind_since");
    public static final List<String> EXTERNAL_SETS = List.of();
    public static final List<String> OUTPUTS = List.of("low_since", "high_since", "behind", "behind_since", "min_behind", "recovered_at");

    /** The inputs; every one starts at 0 (and every external set empty) until set. */
    public static final class Context {
        public double behind;
        public double pressure;
        public double high_since;
        public double hold;
        public double now;
        public double recovered_at;
        public double min_behind;
        public double low_since;
        public double behind_since;
        public Context behind(double v) { this.behind = v; return this; }
        public Context pressure(double v) { this.pressure = v; return this; }
        public Context high_since(double v) { this.high_since = v; return this; }
        public Context hold(double v) { this.hold = v; return this; }
        public Context now(double v) { this.now = v; return this; }
        public Context recovered_at(double v) { this.recovered_at = v; return this; }
        public Context min_behind(double v) { this.min_behind = v; return this; }
        public Context low_since(double v) { this.low_since = v; return this; }
        public Context behind_since(double v) { this.behind_since = v; return this; }
    }

    public static final long High = 0L;
    public static final long Low = 1L;
    public static final long Between = 2L;
    public static final long Unknown = 3L;
    public static final long Changed = 1L;
    public static final long Relapse = 300000L;
    public static final long FirstBackoff = 120000L;
    public static final long MaxBackoff = 3600000L;

    public record Vec3(double x, double y, double z) {}

    public record EntitySpawn(long id, long count, long mask) {}

    public record Signal(long id, long count, long mask) {}

    /** Every name a rule updates, in order of first appearance. */
    public enum Var { low_since, high_since, behind, behind_since, min_behind, recovered_at }
    /** SET replaces the value; ADD adds to it. */
    public enum Op { SET, ADD }
    public record Update(Var var, Op op, double value) {}

    public record Result(List<EntitySpawn> spawns, List<Signal> signals, List<Update> updates) {}

    private static double min2(double a, double b) { return a < b ? a : b; }

    // rule 0 (line 32): [behind == 0] and [pressure != 3]
    static boolean rule0(Context c) {
        return (c.behind == 0.0) && (c.pressure != 3.0);
    }

    // rule 1 (line 33): [behind == 0] and [pressure != 3] and [pressure != 0]
    static boolean rule1(Context c) {
        return (c.behind == 0.0) && (c.pressure != 3.0) && (c.pressure != 0.0);
    }

    // rule 2 (line 36): [behind == 0] and [pressure == 0] and [high_since < 0] and [hold > 0]
    static boolean rule2(Context c) {
        return (c.behind == 0.0) && (c.pressure == 0.0) && (c.high_since < 0.0) && (c.hold > 0.0);
    }

    // rule 3 (line 39): [behind == 0] and [pressure == 0] and ([high_since < 0] and [hold <= 0] or [high_since >= 0] and [now - high_since >= hold])
    static boolean rule3(Context c) {
        return (c.behind == 0.0) && (c.pressure == 0.0) && (((c.high_since < 0.0) && (c.hold <= 0.0)) || ((c.high_since >= 0.0) && (c.now - c.high_since >= c.hold)));
    }

    // rule 4 (line 42): [behind == 0] and [pressure == 0] and ([high_since < 0] and [hold <= 0] or [high_since >= 0] and [now - high_since >= hold]) and [now - recovered_at > 300000]
    static boolean rule4(Context c) {
        return (c.behind == 0.0) && (c.pressure == 0.0) && (((c.high_since < 0.0) && (c.hold <= 0.0)) || ((c.high_since >= 0.0) && (c.now - c.high_since >= c.hold))) && (c.now - c.recovered_at > 300000.0);
    }

    // rule 5 (line 46): [behind == 0] and [pressure == 0] and ([high_since < 0] and [hold <= 0] or [high_since >= 0] and [now - high_since >= hold]) and [now - recovered_at <= 300000] and [min_behind == 0]
    static boolean rule5(Context c) {
        return (c.behind == 0.0) && (c.pressure == 0.0) && (((c.high_since < 0.0) && (c.hold <= 0.0)) || ((c.high_since >= 0.0) && (c.now - c.high_since >= c.hold))) && (c.now - c.recovered_at <= 300000.0) && (c.min_behind == 0.0);
    }

    // rule 6 (line 50): [behind == 0] and [pressure == 0] and ([high_since < 0] and [hold <= 0] or [high_since >= 0] and [now - high_since >= hold]) and [now - recovered_at <= 300000] and [min_behind != 0]
    static boolean rule6(Context c) {
        return (c.behind == 0.0) && (c.pressure == 0.0) && (((c.high_since < 0.0) && (c.hold <= 0.0)) || ((c.high_since >= 0.0) && (c.now - c.high_since >= c.hold))) && (c.now - c.recovered_at <= 300000.0) && (c.min_behind != 0.0);
    }

    // rule 7 (line 56): [behind != 0] and [pressure != 3]
    static boolean rule7(Context c) {
        return (c.behind != 0.0) && (c.pressure != 3.0);
    }

    // rule 8 (line 57): [behind != 0] and [pressure != 3] and [pressure != 1]
    static boolean rule8(Context c) {
        return (c.behind != 0.0) && (c.pressure != 3.0) && (c.pressure != 1.0);
    }

    // rule 9 (line 60): [behind != 0] and [pressure == 1] and ([low_since < 0] and [hold <= 0] or [low_since >= 0] and [now - low_since >= hold]) and [now - behind_since >= min_behind]
    static boolean rule9(Context c) {
        return (c.behind != 0.0) && (c.pressure == 1.0) && (((c.low_since < 0.0) && (c.hold <= 0.0)) || ((c.low_since >= 0.0) && (c.now - c.low_since >= c.hold))) && (c.now - c.behind_since >= c.min_behind);
    }

    // rule 10 (line 66): [behind != 0] and [pressure == 1] and [low_since < 0] and not ([hold <= 0] and [now - behind_since >= min_behind])
    static boolean rule10(Context c) {
        return (c.behind != 0.0) && (c.pressure == 1.0) && (c.low_since < 0.0) && !((c.hold <= 0.0) && (c.now - c.behind_since >= c.min_behind));
    }

    /** The spawns, signals and updates of every rule that holds, in rule order. */
    public static Result evaluate(Context c) {
        List<EntitySpawn> spawns = new ArrayList<>();
        List<Signal> signals = new ArrayList<>();
        List<Update> updates = new ArrayList<>();
        if (rule0(c)) {  // rule 0, line 32
            // low_since <- -1
            updates.add(new Update(Var.low_since, Op.SET, -1.0));
        }
        if (rule1(c)) {  // rule 1, line 33
            // high_since <- -1
            updates.add(new Update(Var.high_since, Op.SET, -1.0));
        }
        if (rule2(c)) {  // rule 2, line 36
            // high_since <- now
            updates.add(new Update(Var.high_since, Op.SET, c.now));
        }
        if (rule3(c)) {  // rule 3, line 39
            // behind <- 1
            updates.add(new Update(Var.behind, Op.SET, 1.0));
            // behind_since <- now
            updates.add(new Update(Var.behind_since, Op.SET, c.now));
            // high_since <- -1
            updates.add(new Update(Var.high_since, Op.SET, -1.0));
            // S(1)
            signals.add(new Signal(1L, 1L, 0L));
        }
        if (rule4(c)) {  // rule 4, line 42
            // min_behind <- 0
            updates.add(new Update(Var.min_behind, Op.SET, 0.0));
        }
        if (rule5(c)) {  // rule 5, line 46
            // min_behind <- 120000
            updates.add(new Update(Var.min_behind, Op.SET, 120000.0));
        }
        if (rule6(c)) {  // rule 6, line 50
            // min_behind <- min(3600000, min_behind * 2)
            updates.add(new Update(Var.min_behind, Op.SET, min2(3600000.0, c.min_behind * 2.0)));
        }
        if (rule7(c)) {  // rule 7, line 56
            // high_since <- -1
            updates.add(new Update(Var.high_since, Op.SET, -1.0));
        }
        if (rule8(c)) {  // rule 8, line 57
            // low_since <- -1
            updates.add(new Update(Var.low_since, Op.SET, -1.0));
        }
        if (rule9(c)) {  // rule 9, line 60
            // behind <- 0
            updates.add(new Update(Var.behind, Op.SET, 0.0));
            // recovered_at <- now
            updates.add(new Update(Var.recovered_at, Op.SET, c.now));
            // low_since <- -1
            updates.add(new Update(Var.low_since, Op.SET, -1.0));
            // S(1)
            signals.add(new Signal(1L, 1L, 0L));
        }
        if (rule10(c)) {  // rule 10, line 66
            // low_since <- now
            updates.add(new Update(Var.low_since, Op.SET, c.now));
        }
        return new Result(List.copyOf(spawns), List.copyOf(signals), List.copyOf(updates));
    }
}
