// Generated by nyrc 0.2.0 (NYR-Lang) from smarttick/src/main/nyr/pressure.nyr -- do not edit.
// source sha256 0d43a3e85ce1a997b185d4ab9b8fe64540e43c67dd2e951304f1a1a33c3c5a12
package com.nyr.guardian.smarttick;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * Rules compiled from smarttick/src/main/nyr/pressure.nyr by nyrc 0.2.0.  {@link #evaluate(Context)} returns the spawns,
 * signals and updates of every rule whose condition holds, in rule order.  Numbers are double;
 * an update's {@link Op} says whether it replaces (SET) or adds to (ADD) the output it names.
 */
public final class PressureRules {
    private PressureRules() {}

    public static final List<String> INPUTS = List.of("unit", "value", "mspt_sleep_at", "mspt_wake_at", "tps_sleep_below", "tps_wake_at");
    public static final List<String> EXTERNAL_SETS = List.of();
    public static final List<String> OUTPUTS = List.of();

    /** The inputs; every one starts at 0 (and every external set empty) until set. */
    public static final class Context {
        public double unit;
        public double value;
        public double mspt_sleep_at;
        public double mspt_wake_at;
        public double tps_sleep_below;
        public double tps_wake_at;
        public Context unit(double v) { this.unit = v; return this; }
        public Context value(double v) { this.value = v; return this; }
        public Context mspt_sleep_at(double v) { this.mspt_sleep_at = v; return this; }
        public Context mspt_wake_at(double v) { this.mspt_wake_at = v; return this; }
        public Context tps_sleep_below(double v) { this.tps_sleep_below = v; return this; }
        public Context tps_wake_at(double v) { this.tps_wake_at = v; return this; }
    }

    public static final long High = 0L;
    public static final long Low = 1L;
    public static final long Between = 2L;

    public record Vec3(double x, double y, double z) {}

    public record EntitySpawn(long id, long count, long mask) {}

    public record Signal(long id, long count, long mask) {}

    /** Every name a rule updates, in order of first appearance. */
    public enum Var {}
    /** SET replaces the value; ADD adds to it. */
    public enum Op { SET, ADD }
    public record Update(Var var, Op op, double value) {}

    public record Result(List<EntitySpawn> spawns, List<Signal> signals, List<Update> updates) {}


    // rule 0 (line 15): [unit == 0] and [value >= mspt_sleep_at]
    static boolean rule0(Context c) {
        return (c.unit == 0.0) && (c.value >= c.mspt_sleep_at);
    }

    // rule 1 (line 16): [unit == 0] and not [value >= mspt_sleep_at] and [value <= mspt_wake_at]
    static boolean rule1(Context c) {
        return (c.unit == 0.0) && !(c.value >= c.mspt_sleep_at) && (c.value <= c.mspt_wake_at);
    }

    // rule 2 (line 17): [unit == 0] and not [value >= mspt_sleep_at] and not [value <= mspt_wake_at]
    static boolean rule2(Context c) {
        return (c.unit == 0.0) && !(c.value >= c.mspt_sleep_at) && !(c.value <= c.mspt_wake_at);
    }

    // rule 3 (line 19): [unit != 0] and [value < tps_sleep_below]
    static boolean rule3(Context c) {
        return (c.unit != 0.0) && (c.value < c.tps_sleep_below);
    }

    // rule 4 (line 20): [unit != 0] and not [value < tps_sleep_below] and [value >= tps_wake_at]
    static boolean rule4(Context c) {
        return (c.unit != 0.0) && !(c.value < c.tps_sleep_below) && (c.value >= c.tps_wake_at);
    }

    // rule 5 (line 21): [unit != 0] and not [value < tps_sleep_below] and not [value >= tps_wake_at]
    static boolean rule5(Context c) {
        return (c.unit != 0.0) && !(c.value < c.tps_sleep_below) && !(c.value >= c.tps_wake_at);
    }

    /** The spawns, signals and updates of every rule that holds, in rule order. */
    public static Result evaluate(Context c) {
        List<EntitySpawn> spawns = new ArrayList<>();
        List<Signal> signals = new ArrayList<>();
        List<Update> updates = new ArrayList<>();
        if (rule0(c)) {  // rule 0, line 15
            // S(0)
            signals.add(new Signal(0L, 1L, 0L));
        }
        if (rule1(c)) {  // rule 1, line 16
            // S(1)
            signals.add(new Signal(1L, 1L, 0L));
        }
        if (rule2(c)) {  // rule 2, line 17
            // S(2)
            signals.add(new Signal(2L, 1L, 0L));
        }
        if (rule3(c)) {  // rule 3, line 19
            // S(0)
            signals.add(new Signal(0L, 1L, 0L));
        }
        if (rule4(c)) {  // rule 4, line 20
            // S(1)
            signals.add(new Signal(1L, 1L, 0L));
        }
        if (rule5(c)) {  // rule 5, line 21
            // S(2)
            signals.add(new Signal(2L, 1L, 0L));
        }
        return new Result(List.copyOf(spawns), List.copyOf(signals), List.copyOf(updates));
    }
}
